; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_CHARMANDER ; 4
	const DEX_CHARMELEON ; 5
	const DEX_CHARIZARD  ; 6
	const DEX_SQUIRTLE   ; 7
	const DEX_WARTORTLE  ; 8
	const DEX_BLASTOISE  ; 9
	const DEX_CATERPIE   ; 10
	const DEX_METAPOD    ; 11
	const DEX_BUTTERFREE ; 12
	const DEX_WEEDLE     ; 13
	const DEX_KAKUNA     ; 14
	const DEX_BEEDRILL   ; 15
	const DEX_PIDGEY     ; 16
	const DEX_PIDGEOTTO  ; 17
	const DEX_PIDGEOT    ; 18
	const DEX_RATTATA    ; 19
	const DEX_RATICATE   ; 20
	const DEX_SPEAROW    ; 21
	const DEX_FEAROW     ; 22
	const DEX_EKANS      ; 23
	const DEX_ARBOK      ; 24
	const DEX_PICHU      ; 25
	const DEX_PIKACHU    ; 26
	const DEX_RAICHU     ; 27
	const DEX_GOROCHU    ; 28
	const DEX_SANDSHREW  ; 29
	const DEX_SANDSLASH  ; 30
	const DEX_NIDORAN_F  ; 31
	const DEX_NIDORINA   ; 32
	const DEX_NIDOQUEEN  ; 33
	const DEX_NIDORAN_M  ; 34
	const DEX_NIDORINO   ; 35
	const DEX_NIDOKING   ; 36
	const DEX_CLEFFA     ; 37
	const DEX_CLEFAIRY   ; 38
	const DEX_CLEFABLE   ; 39
	const DEX_VULPIX     ; 40
	const DEX_NINETALES  ; 41
	const DEX_IGGLYBUFF  ; 42
	const DEX_JIGGLYPUFF ; 43
	const DEX_WIGGLYTUFF ; 44
	const DEX_TOGEPI     ; 45
	const DEX_TOGETIC    ; 46
	const DEX_TOGEKISS   ; 47
	const DEX_ZUBAT      ; 48
	const DEX_GOLBAT     ; 49
	const DEX_CROBAT     ; 50
	const DEX_ODDISH     ; 51
	const DEX_GLOOM      ; 52
	const DEX_VILEPLUME  ; 53
	const DEX_BELLOSSOM  ; 54
	const DEX_HOPPIP     ; 55
	const DEX_SKIPLOOM   ; 56
	const DEX_JUMPLUFF   ; 57
	const DEX_PARAS      ; 58
	const DEX_PARASECT   ; 59
	const DEX_VENONAT    ; 60
	const DEX_VENOMOTH   ; 61
	const DEX_JOLTIK     ; 62
	const DEX_GALVANTULA ; 63
	const DEX_DIGLETT    ; 64
	const DEX_DUGTRIO    ; 65
	const DEX_MEOWTH     ; 66
	const DEX_PERSIAN    ; 67
	const DEX_CHIMEOW    ; 68
	const DEX_BELLUNA    ; 69
	const DEX_MAREEP     ; 70
	const DEX_FLAAFFY    ; 71
	const DEX_AMPHAROS   ; 72
	const DEX_PSYDUCK    ; 73
	const DEX_GOLDUCK    ; 74
	const DEX_MANKEY     ; 75
	const DEX_PRIMEAPE   ; 76
	const DEX_GROWLITHE  ; 77
	const DEX_ARCANINE   ; 78
	const DEX_HOUNDOUR   ; 79
	const DEX_HOUNDOOM   ; 80
	const DEX_POLIWAG    ; 81
	const DEX_POLIWHIRL  ; 82
	const DEX_POLIWRATH  ; 83
	const DEX_POLITOED   ; 84
	const DEX_ABRA       ; 85
	const DEX_KADABRA    ; 86
	const DEX_ALAKAZAM   ; 87
	const DEX_MACHOP     ; 88
	const DEX_MACHOKE    ; 89
	const DEX_MACHAMP    ; 90
	const DEX_BELLSPROUT ; 91
	const DEX_WEEPINBELL ; 92
	const DEX_VICTREEBEL ; 93
	const DEX_TENTACOOL  ; 94
	const DEX_TENTACRUEL ; 95
	const DEX_GEODUDE    ; 96
	const DEX_GRAVELER   ; 97
	const DEX_GOLEM      ; 98
	const DEX_WHISMUR    ; 99
	const DEX_LOUDRED    ; 100
	const DEX_EXPLOUD    ; 101
	const DEX_CROAGUNK   ; 102
	const DEX_TOXICROAK  ; 103
	const DEX_PONYTA     ; 104
	const DEX_RAPIDASH   ; 105
	const DEX_SALANDIT   ; 106
	const DEX_SALAZZLE   ; 107
	const DEX_SLOWPOKE   ; 108
	const DEX_SLOWBRO    ; 109
	const DEX_SLOWKING   ; 110
	const DEX_MAGNEMITE  ; 111
	const DEX_MAGNETON   ; 112
	const DEX_MAGNEZONE  ; 113
	const DEX_FARFETCHD  ; 114
	const DEX_DODUO      ; 115
	const DEX_DODRIO     ; 116
	const DEX_MURKROW    ; 117
	const DEX_HONCHKROW  ; 118
	const DEX_SKARMORY   ; 119
	const DEX_SEEL       ; 120
	const DEX_DEWGONG    ; 121
	const DEX_SNEASEL    ; 122
	const DEX_WEAVILE    ; 123
	const DEX_SWINUB     ; 124
	const DEX_PILOSWINE  ; 125
	const DEX_MAMOSWINE  ; 126
	const DEX_GRIMER     ; 127
	const DEX_MUK        ; 128
	const DEX_SHELLDER   ; 129
	const DEX_CLOYSTER   ; 130
	const DEX_TURBAN     ; 131
	const DEX_GASTLY     ; 132
	const DEX_HAUNTER    ; 133
	const DEX_GENGAR     ; 134
	const DEX_DUSKULL    ; 135
	const DEX_DUSCLOPS   ; 136
	const DEX_DUSKNOIR   ; 137
	const DEX_LITWICK    ; 138
	const DEX_LAMPENT    ; 139
	const DEX_CHANDELURE ; 140
	const DEX_ONIX       ; 141
	const DEX_STEELIX    ; 142
	const DEX_GLIGAR     ; 143
	const DEX_GLISCOR    ; 144
	const DEX_DROWZEE    ; 145
	const DEX_HYPNO      ; 146
	const DEX_KRABBY     ; 147
	const DEX_KINGLER    ; 148
	const DEX_VOLTORB    ; 149
	const DEX_ELECTRODE  ; 150
	const DEX_EXEGGCUTE  ; 151
	const DEX_EXEGGUTOR  ; 152
	const DEX_CUBONE     ; 153
	const DEX_MAROWAK    ; 154
	const DEX_MAWILE     ; 155
	const DEX_TRAPINCH   ; 156
	const DEX_VIBRAVA    ; 157
	const DEX_FLYGON     ; 158
	const DEX_NOIBAT     ; 159
	const DEX_NOIVERN    ; 160
	const DEX_TYROGUE    ; 161
	const DEX_HITMONLEE  ; 162
	const DEX_HITMONCHAN ; 163
	const DEX_HITMONTOP  ; 164
	const DEX_LICKITUNG  ; 165
	const DEX_LICKILICKY ; 166
	const DEX_KOFFING    ; 167
	const DEX_WEEZING    ; 168
	const DEX_RHYHORN    ; 169
	const DEX_RHYDON     ; 170
	const DEX_RHYPERIOR  ; 171
	const DEX_HAPPINY    ; 172
	const DEX_CHANSEY    ; 173
	const DEX_BLISSEY    ; 174
	const DEX_TANGELA    ; 175
	const DEX_TANGROWTH  ; 176
	const DEX_KANGASKHAN ; 177
	const DEX_HORSEA     ; 178
	const DEX_SEADRA     ; 179
	const DEX_KINGDRA    ; 180
	const DEX_GOLDEEN    ; 181
	const DEX_SEAKING    ; 182
	const DEX_STARYU     ; 183
	const DEX_STARMIE    ; 184
	const DEX_MIME_JR    ; 185
	const DEX_MR_MIME    ; 186
	const DEX_SCYTHER    ; 187
	const DEX_SCIZOR     ; 188
	const DEX_SMOOCHUM   ; 189
	const DEX_JYNX       ; 190
	const DEX_ELEKID     ; 191
	const DEX_ELECTABUZZ ; 192
	const DEX_ELECTIVIRE ; 193
	const DEX_MAGBY      ; 194
	const DEX_MAGMAR     ; 195
	const DEX_MAGMORTAR  ; 196
	const DEX_PINSIR     ; 197
	const DEX_HERACROSS  ; 198
	const DEX_TAUROS     ; 199
	const DEX_MILTANK    ; 200
	const DEX_MAGIKARP   ; 201
	const DEX_GYARADOS   ; 202
	const DEX_LAPRAS     ; 203
	const DEX_DITTO      ; 204
	const DEX_EEVEE      ; 205
	const DEX_VAPOREON   ; 206
	const DEX_JOLTEON    ; 207
	const DEX_FLAREON    ; 208
	const DEX_ESPEON     ; 209
	const DEX_UMBREON    ; 210
	const DEX_LEAFEON    ; 211
	const DEX_GLACEON    ; 212
	const DEX_SYLVEON    ; 213
	const DEX_PORYGON    ; 214
	const DEX_PORYGON2   ; 215
	const DEX_PORYGONZ   ; 216
	const DEX_OMANYTE    ; 217
	const DEX_OMASTAR    ; 218
	const DEX_KABUTO     ; 219
	const DEX_KABUTOPS   ; 220
	const DEX_AERODACTYL ; 221
	const DEX_MUNCHLAX   ; 222
	const DEX_SNORLAX    ; 223
	const DEX_BONSLY     ; 224
	const DEX_SUDOWOODO  ; 225
	const DEX_SPIRITOMB  ; 226
	const DEX_ARTICUNO   ; 227
	const DEX_ZAPDOS     ; 228
	const DEX_MOLTRES    ; 229
	const DEX_THUFIZER   ; 230
	const DEX_REGIROCK   ; 231
	const DEX_REGICE     ; 232
	const DEX_REGISTEEL  ; 233
	const DEX_SKELETOPS  ; 234
	const DEX_OSSIDACTYL ; 235
	const DEX_DRATINI    ; 236
	const DEX_DRAGONAIR  ; 237
	const DEX_DRAGONITE  ; 238
	const DEX_LARVITAR   ; 239
	const DEX_PUPITAR    ; 240
	const DEX_TYRANITAR  ; 241
	const DEX_BAGON      ; 242
	const DEX_SHELGON    ; 243
	const DEX_SALAMENCE  ; 244
	const DEX_BELDUM     ; 245
	const DEX_METANG     ; 246
	const DEX_METAGROSS  ; 247
	const DEX_REGIGIGAS  ; 248
	const DEX_MEWTWO     ; 249
	const DEX_MEW        ; 250
	const DEX_YOSHI      ; 251
	const DEX_MISSINGNO  ; 252

DEF NUM_POKEMON EQU const_value - 1
