SafariZoneWestRestHouse_Script:
	call EnableAutoTextBoxDrawing
	ret

SafariZoneWestRestHouse_TextPointers:
	def_text_pointers
	dw_const SafariZoneWestRestHouseScientistText,    TEXT_SAFARIZONEWESTRESTHOUSE_SCIENTIST
	dw_const SafariZoneWestRestHouseCooltrainerMText, TEXT_SAFARIZONEWESTRESTHOUSE_COOLTRAINER_M
	dw_const SafariZoneWestRestHouseSilphWorkerFText, TEXT_SAFARIZONEWESTRESTHOUSE_SILPH_WORKER_F
	dw_const SafariZoneWestRestHouseStepSellerText,   TEXT_SAFARIZONEWESTRESTHOUSE_STEP_SELLER
	dw_const SafariZoneWestRestHouseDetailsText,      TEXT_SAFARIZONEWESTRESTHOUSE_DETAILS

SafariZoneWestRestHouseScientistText:
	text_far _SafariZoneWestRestHouseScientistText
	text_end

SafariZoneWestRestHouseCooltrainerMText:
	text_far _SafariZoneWestRestHouseCooltrainerMText
	text_end

SafariZoneWestRestHouseSilphWorkerFText:
	text_far _SafariZoneWestRestHouseSilphWorkerFText
	text_end
	
SafariZoneWestRestHouseDetailsText:
	text_far _SafariZoneRestHousePosterText
	text_end
	text_far _SafariZoneWestRestHouseDetailsText
	text_end
	
SafariZoneWestRestHouseStepSellerText: ; ~$~ADDED: Buy more steps in rest houses.~$~
	text_asm
	call StepSellerScript
	jp TextScriptEnd
