ViridianSchoolHouse_Script:
	jp EnableAutoTextBoxDrawing

ViridianSchoolHouse_TextPointers:
	def_text_pointers
	dw_const ViridianSchoolHouseMCText,      TEXT_VIRIDIANSCHOOLHOUSE_MC
	dw_const ViridianSchoolHouseMonikaText,  TEXT_VIRIDIANSCHOOLHOUSE_MONIKA
	dw_const ViridianSchoolHouseSayoriText,  TEXT_VIRIDIANSCHOOLHOUSE_SAYORI
	dw_const ViridianSchoolHouseYuriText,    TEXT_VIRIDIANSCHOOLHOUSE_YURI
	dw_const ViridianSchoolHouseNatsukiText, TEXT_VIRIDIANSCHOOLHOUSE_NATSUKI

ViridianSchoolHouseMCText:
	text_far _ViridianSchoolHouseMCText
	text_end

ViridianSchoolHouseMonikaText:
	text_far _ViridianSchoolHouseMonikaText
	text_end
	
ViridianSchoolHouseSayoriText:
	text_far _ViridianSchoolHouseSayoriText
	text_end
	
ViridianSchoolHouseYuriText:
	text_far _ViridianSchoolHouseYuriText
	text_end
	
ViridianSchoolHouseNatsukiText:
	text_far _ViridianSchoolHouseNatsukiText
	text_end
