PlayerFishingTilesFront:  INCBIN "gfx/overworld/player_fish_front.2bpp"
PlayerFishingTilesBack:   INCBIN "gfx/overworld/player_fish_back.2bpp"
PlayerFishingTilesSide:   INCBIN "gfx/overworld/player_fish_side.2bpp"
PlayerFishingRodTiles:    INCBIN "gfx/overworld/fishing_rod.2bpp"
PlayerFFishingTilesFront: INCBIN "gfx/overworld/player_f_fish_front.2bpp"
PlayerFFishingTilesBack:  INCBIN "gfx/overworld/player_f_fish_back.2bpp"
PlayerFFishingTilesSide:  INCBIN "gfx/overworld/player_f_fish_side.2bpp"
