; ~$~ADDED: Red++'s version of the Physical/Special split.~$~
_PhysicalSpecialSplit:: ;Determines if a move is Physical or Special
	ld a, [wTempMoveID]
	ld c,a
	ld b, $00
	ld hl,.MovesTable
	add hl,bc
	ld a,[hl]
	ld [wTempMoveID], a
	ret

	
.MovesTable
	db OTHER_M ;NOTHING
	db PHYSICAL;POUND
	db PHYSICAL;KARATE_CHOP
	db PHYSICAL;DOUBLE_HIT
	db PHYSICAL;BULLET_PUNCH
	db PHYSICAL;MEGA_PUNCH
	db PHYSICAL;PAY_DAY
	db PHYSICAL;FIRE_PUNCH
	db PHYSICAL;ICE_PUNCH
	db PHYSICAL;THUNDERPUNCH
	db PHYSICAL;SCRATCH
	db PHYSICAL;VICEGRIP
	db PHYSICAL;GUILLOTINE
	db SPECIAL ;RAZOR_WIND
	db OTHER_M ;SWORDS_DANCE
	db PHYSICAL;CUT
	db SPECIAL ;GUST
	db PHYSICAL;WING_ATTACK
	db SPECIAL ;HURRICANE
	db PHYSICAL;FLY
	db PHYSICAL;BIND
	db PHYSICAL;BREAK_SWIPE
	db PHYSICAL;VINE_WHIP
	db PHYSICAL;STOMP
	db PHYSICAL;DOUBLE_KICK
	db PHYSICAL;MEGA_KICK
	db PHYSICAL;BLAZE_KICK
	db PHYSICAL;ROLLING_KICK
	db OTHER_M ;SAND_ATTACK
	db PHYSICAL;HEADBUTT
	db PHYSICAL;HORN_ATTACK
	db PHYSICAL;FURY_ATTACK
	db PHYSICAL;SMART_STRIKE
	db PHYSICAL;TACKLE
	db PHYSICAL;BODY_SLAM
	db SPECIAL ;WHIRLPOOL
	db PHYSICAL;TAKE_DOWN
	db PHYSICAL;THRASH
	db PHYSICAL;DOUBLE_EDGE
	db OTHER_M ;TAIL_WHIP
	db PHYSICAL;POISON_STING
	db PHYSICAL;TWINEEDLE
	db PHYSICAL;PIN_MISSILE
	db OTHER_M ;LEER
	db PHYSICAL;BITE
	db OTHER_M ;GROWL
	db OTHER_M ;HOWL
	db OTHER_M ;SING
	db OTHER_M ;SUPERSONIC
	db SPECIAL ;SONICBOOM
	db OTHER_M ;DISABLE
	db SPECIAL ;ACID
	db SPECIAL ;EMBER
	db SPECIAL ;FLAMETHROWER
	db OTHER_M ;MIST
	db SPECIAL ;WATER_GUN
	db SPECIAL ;HYDRO_PUMP
	db SPECIAL ;SURF
	db SPECIAL ;ICE_BEAM
	db SPECIAL ;BLIZZARD
	db SPECIAL ;PSYBEAM
	db SPECIAL ;BUBBLEBEAM
	db SPECIAL ;AURORA_BEAM
	db SPECIAL ;HYPER_BEAM
	db PHYSICAL;PECK
	db PHYSICAL;DRILL_PECK
	db PHYSICAL;SUBMISSION
	db PHYSICAL;LOW_SWEEP
	db PHYSICAL;COUNTER
	db PHYSICAL;SEISMIC_TOSS
	db PHYSICAL;STRENGTH
	db SPECIAL ;GIGA_DRAIN
	db SPECIAL ;MEGA_DRAIN
	db OTHER_M ;LEECH_SEED
	db OTHER_M ;GROWTH
	db PHYSICAL;RAZOR_LEAF
	db SPECIAL ;SOLARBEAM
	db OTHER_M ;POISONPOWDER
	db OTHER_M ;STUN_SPORE
	db OTHER_M ;SLEEP_POWDER
	db SPECIAL ;PETAL_DANCE
	db OTHER_M ;STRING_SHOT
	db SPECIAL ;DRAGONBREATH
	db SPECIAL ;FIRE_SPIN
	db SPECIAL ;THUNDERSHOCK
	db SPECIAL ;THUNDERBOLT
	db OTHER_M ;THUNDER_WAVE
	db SPECIAL ;THUNDER
	db PHYSICAL;ROCK_THROW
	db PHYSICAL;EARTHQUAKE
	db PHYSICAL;FISSURE
	db PHYSICAL;DIG
	db OTHER_M ;TOXIC
	db SPECIAL ;CONFUSION
	db SPECIAL ;PSYCHIC_M
	db OTHER_M ;HYPNOSIS
	db OTHER_M ;MEDITATE
	db OTHER_M ;AGILITY
	db PHYSICAL;QUICK_ATTACK
	db PHYSICAL;OUTRAGE
	db OTHER_M ;TELEPORT
	db SPECIAL ;NIGHT_SHADE
	db OTHER_M ;MIMIC
	db OTHER_M ;SCREECH
	db OTHER_M ;DOUBLE_TEAM
	db OTHER_M ;RECOVER
	db OTHER_M ;HARDEN
	db OTHER_M ;MINIMIZE
	db OTHER_M ;SMOKESCREEN
	db OTHER_M ;CONFUSE_RAY
	db OTHER_M ;IRON_DEFENSE
	db OTHER_M ;PROTECT
	db OTHER_M ;BARRIER
	db OTHER_M ;LIGHT_SCREEN
	db OTHER_M ;HAZE
	db OTHER_M ;REFLECT
	db OTHER_M ;FOCUS_ENERGY
	db PHYSICAL;METEOR_MASH
	db OTHER_M ;METRONOME
	db OTHER_M ;MIRROR_MOVE
	db PHYSICAL;SELFDESTRUCT
	db PHYSICAL;EGG_BOMB
	db PHYSICAL;LICK
	db SPECIAL ;SMOG
	db SPECIAL ;SLUDGE
	db PHYSICAL;BONE_CLUB
	db SPECIAL ;FIRE_BLAST
	db PHYSICAL;WATERFALL
	db PHYSICAL;CLAMP
	db SPECIAL ;SWIFT
	db PHYSICAL;GIGA_IMPACT
	db PHYSICAL;ICICLE_SPEAR
	db PHYSICAL;ASTONISH
	db OTHER_M ;AMNESIA
	db OTHER_M ;COSMIC_POWER
	db OTHER_M ;SOFTBOILED
	db PHYSICAL;HI_JUMP_KICK
	db OTHER_M ;GLARE
	db SPECIAL ;DREAM_EATER
	db OTHER_M ;POISON_GAS
	db PHYSICAL;BULLET_SEED
	db PHYSICAL;LEECH_LIFE
	db OTHER_M ;LOVELY_KISS
	db PHYSICAL;SKY_ATTACK
	db OTHER_M ;TRANSFORM
	db SPECIAL ;WATER_PULSE
	db PHYSICAL;DIZZY_PUNCH
	db OTHER_M ;SPORE
	db OTHER_M ;FLASH
	db SPECIAL ;ZEN_HEADBUTT
	db OTHER_M ;SPLASH
	db OTHER_M ;ACID_ARMOR
	db PHYSICAL;CRABHAMMER
	db PHYSICAL;EXPLOSION
	db PHYSICAL;DRAGON_CLAW
	db PHYSICAL;BONEMERANG
	db OTHER_M ;REST
	db PHYSICAL;ROCK_SLIDE
	db PHYSICAL;POISON_FANG
	db OTHER_M ;SHARPEN
	db OTHER_M ;CONVERSION
	db SPECIAL ;TRI_ATTACK
	db PHYSICAL;SUPER_FANG
	db PHYSICAL;SLASH
	db OTHER_M ;SUBSTITUTE
	db PHYSICAL;STRUGGLE
; ~$~ADDED: New moves.~$~
	db OTHER_M ;CURSE
	db OTHER_M ;COTTON_SPORE
	db SPECIAL ;POWDER_SNOW
	db PHYSICAL;MACH_PUNCH
	db OTHER_M ;SCARY_FACE
	db PHYSICAL;FEINT_ATTACK
	db OTHER_M ;SWEET_KISS
	db SPECIAL ;SLUDGE_BOMB
	db SPECIAL ;MUD_SLAP
	db SPECIAL ;ZAP_CANNON
	db SPECIAL ;ICY_WIND
	db OTHER_M ;CHARM
	db PHYSICAL;SPARK
	db PHYSICAL;STEEL_WING
	db OTHER_M ;HEAL_BELL
	db OTHER_M ;SAFEGUARD
	db PHYSICAL;DYNAMICPUNCH
	db PHYSICAL;MEGAHORN
	db PHYSICAL;RAPID_SPIN
	db PHYSICAL;IRON_TAIL
	db PHYSICAL;METAL_CLAW
	db PHYSICAL;CROSS_CHOP
	db SPECIAL ;TWISTER
	db PHYSICAL;CRUNCH
	db SPECIAL ;MIRROR_COAT
	db PHYSICAL;EXTREMESPEED
	db SPECIAL ;ANCIENTPOWER
	db SPECIAL ;SHADOW_BALL
	db OTHER_M ;WILL_O_WISP
	db SPECIAL ;HYPER_VOICE
	db OTHER_M ;FAKE_TEARS
	db PHYSICAL;ROCK_TOMB
	db SPECIAL ;SILVER_WIND
	db OTHER_M ;METAL_SOUND
	db SPECIAL ;SIGNAL_BEAM
	db PHYSICAL;SAND_TOMB
	db SPECIAL ;SHEER_COLD
	db PHYSICAL;AERIAL_ACE
	db SPECIAL ;MUD_SHOT
	db SPECIAL ;MAGICAL_LEAF
	db OTHER_M ;DRAGON_DANCE
	db SPECIAL ;SHOCK_WAVE
	db PHYSICAL;SUCKER_PUNCH
	db PHYSICAL;FLARE_BLITZ
	db PHYSICAL;POISON_JAB
	db SPECIAL ;DARK_PULSE
	db PHYSICAL;NIGHT_SLASH
	db SPECIAL ;AIR_SLASH
	db PHYSICAL;X_SCISSOR
	db SPECIAL ;BUG_BUZZ
	db SPECIAL ;DRAGON_PULSE
	db SPECIAL ;POWER_GEM
	db PHYSICAL;DRAIN_PUNCH
	db SPECIAL ;FOCUS_BLAST
	db SPECIAL ;ENERGY_BALL
	db SPECIAL ;EARTH_POWER
	db OTHER_M ;NASTY_PLOT
	db PHYSICAL;ICE_SHARD
	db PHYSICAL;SHADOW_CLAW
	db PHYSICAL;THUNDER_FANG
	db PHYSICAL;ICE_FANG
	db PHYSICAL;FIRE_FANG
	db PHYSICAL;SHADOW_SNEAK
	db SPECIAL ;FLASH_CANNON
	db PHYSICAL;POWER_WHIP
	db PHYSICAL;ROCK_WRECKER
	db PHYSICAL;GUNK_SHOT
	db PHYSICAL;IRON_HEAD
	db PHYSICAL;STONE_EDGE
	db SPECIAL ;OMINOUS_WIND
	db PHYSICAL;FLAME_CHARGE
	db SPECIAL ;SCALD
	db SPECIAL ;HEX
	db SPECIAL ;INFERNO
	db PHYSICAL;BULLDOZE
	db SPECIAL ;ELECTROWEB
	db PHYSICAL;WILD_CHARGE
	db SPECIAL ;PSYSTRIKE
	db SPECIAL ;SNARL
	db PHYSICAL;ICICLE_CRASH
	db SPECIAL ;DISARM_VOICE
	db SPECIAL ;DRAIN_KISS
	db PHYSICAL;PLAY_ROUGH
	db SPECIAL ;MOONBLAST
	db SPECIAL ;BOOMBURST
	db SPECIAL ;DAZZLINGLEAM
	db SPECIAL ;INFESTATION
	db PHYSICAL;BRUTAL_SWING
	db PHYSICAL;LIQUIDATION